name: Build binaries

on:
  push:
    paths: [ src/**.cpp, src/**.hpp, CMakeLists.txt ]

  pull_request:
    branches: [ main, dev ]
    paths: [ src/**.cpp, src/**.hpp, CMakeLists.txt ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-11 ]

    name: Build binaries
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build binaries
        run: cmake -j 8 --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}